### PR TITLE
Made IgnoredResourceExtensions configurable from the config

### PR DESCRIPTION
**Pull request by M15sy**
Great tool but I wanted to choose which file extensions to ignore myself so now I am now pulling this from the config as shown in Custom404Handler.cs line 21. 
Github seemed to pick up on all the white space and autogen code :/

### CODE REVIEW

**Comment by evest** [comment]
Thanks, this is a nice addition. Will have to double check it in another diff tool first, seems we have different tab-settings or something, everything is marked as changed :-)

**Comment by M15sy** [comment]
So it looks like I had Windows line endings and you had Unix line endings so I've amended mine to be the same as yours so it should be easier to see whats changed now. 
Thanks

**Comment by fatso83** [comment]
If it happens again, just append [?w=1](https://github.com/BVNetwork/404handler/pull/7/files?w=1) to the url to ignore whitespace changes. It's the same as running `git diff -w`.

**Comment by evest** [comment]
Merged, will be in next release.

**Comment by M15sy** [comment]
Thanks guys!
Looking forward to the next release :)

**Pull request merged**
